FROM tensorflow/tensorflow:2.16.1-gpu

WORKDIR /app

COPY requirements_api.txt .

RUN pip install --no-cache-dir -r requirements_api.txt
COPY src/ /app/src/

EXPOSE 8000

WORKDIR /app/src

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]