FROM tensorflow/tensorflow:2.16.1-gpu

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir \
    fastapi==0.115.0 \
    "uvicorn[standard]==0.30.6" \
    pillow==10.4.0 \
    numpy==1.26.4 \
    matplotlib==3.9.2 \
    python-multipart==0.0.9 \
    scikit-learn==1.5.1 \
    pandas==2.2.2

COPY src/ /app/src/

RUN mkdir -p /app/models
RUN mkdir -p /app/generated/heatmaps

WORKDIR /app/src

CMD ["python", "train.py", \
    "--train_dir", "/app/data/train", \
    "--val_dir", "/app/data/val", \
    "--output_model", "/app/models/best_model.keras", \
    "--output_classes", "/app/models/class_names.json"]