FROM tensorflow/tensorflow:2.16.1-gpu

WORKDIR /app

COPY requirements.txt .

RUN pip install --no-cache-dir \
    fastapi==0.115.0 \
    "uvicorn[standard]==0.30.6" \
    pillow==10.4.0 \
    numpy==1.26.4 \
    matplotlib==3.9.2 \
    python-multipart==0.0.9 \
    scikit-learn==1.5.1 \
    pandas==2.2.2 \
    prometheus-fastapi-instrumentator==6.1.0

COPY src/ /app/src/

EXPOSE 8000

WORKDIR /app/src

CMD ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000"]