services:
  train-manual:
    build:
      context: .
      dockerfile: Dockerfile.train
    container_name: brain-tumor-train-manual
    volumes:
      - ./data:/app/data
      - ./models:/app/models
      - ./generated:/app/generated
    gpus: all

  api-manual:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: brain-tumor-api-manual
    ports:
      - "8000:8000"
    environment:
      MODEL_PATH: /app/models/best_model.keras
      CLASSES_PATH: /app/models/class_names.json
      HEATMAPS_DIR: /app/generated/heatmaps
    volumes:
      - ./models:/app/models
      - ./generated:/app/generated
    gpus: all
  
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-server
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - api-manual # Espera a que la API arranque primero

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-dashboard
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin # Contraseña por defecto (cámbiala si lo subes a un servidor público)
    depends_on:
      - prometheus
  
  retrain-trigger:
    build: 
      context: .
      dockerfile: Dockerfile.webhook
    container_name: retrain-trigger
    volumes:
      - .:/app
      - /var/run/docker.sock:/var/run/docker.sock
    command: python3 src/webhook_receiver.py
    ports:
      - "127.0.0.1:9091:9010"  # <--- Forzamos la IP local 127.0.0.1 y el puerto 9091
    environment:
      - PYTHONUNBUFFERED=1
    
volumes:
  grafana-storage: 
    driver: local